---
title: "R Notebook"
output: html_notebook
---

# Methodology

```{r}
citation('stats')
citation('forecast')
citation('tseries')
```

```{r}
load('data/initial_data_occ_df_final.Rdata')
col_mis_w  = wes_palette('Zissou1',4)[1]
col_mis_s  = wes_palette('Zissou1',4)[3]                  
col_otb_w  = wes_palette('Zissou1',4)[2]
col_otb_s  = wes_palette('Zissou1',4)[4]
```

package \textit{stats}
package \textit{forecast}

# PreProcess

```{r}
a = Sys.time()
## Weekly

ts_w_MIS_W = df_effort_w %>%
  filter(fill %in% c('1-Western Coast 1-Polyvalent')) %>% 
  ungroup() %>% 
  dplyr::select(catch) %>% 
  ts(start = c(1995, 1), end= c(2022,52), frequency = 52)

ts_w_MIS_S = df_effort_w %>%
  filter(fill %in% c('2-Southern Coast 1-Polyvalent')) %>% 
  ungroup() %>% 
  dplyr::select(catch) %>% 
  ts(start = c(1995, 1), end= c(2022,52), frequency = 52)

ts_y_MIS_W = df_effort_y %>%
  filter(fill %in% c('1-Western Coast 1-Polyvalent')) %>% 
  ungroup() %>% 
  dplyr::select(catch) %>% 
  ts(start = c(1995), end= c(2022), frequency = 1)

ts_y_MIS_S = df_effort_y %>%
  filter(fill %in% c('2-Southern Coast 1-Polyvalent')) %>% 
  ungroup() %>% 
  dplyr::select(catch) %>% 
  ts(start = c(1995), end= c(2022), frequency = 1)

b = Sys.time()
perf_boxjenkins_preproc = b-a
```

# Model Fit

```{r}
a = Sys.time()
estacionaridade = c()
series = c('ts_w_MIS_W',
           'ts_w_MIS_S',
           'ts_y_MIS_W',
           'ts_y_MIS_S')

for(i in series){
  temp = get(i)
  res = tseries::adf.test(temp, alternative='s') # pvalue = 0.01
  estacionaridade[length(estacionaridade)+1] = res$p.value
  rm(temp, res)
}

diferenca_ns = c()
diferenca_s = c()

for(i in 1:4){
  temp = get(series[i])
  res_ns = ndiffs(temp)
  diferenca_ns[length(diferenca_ns)+1] = res_ns
  if(i %in% c(1:2)){
    diferenca_s[length(diferenca_s)+1] = nsdiffs(temp)}
    else{diferenca_s[length(diferenca_s)+1] = NA}
  rm(temp, res_ns)
}

tab_estac = data.frame('fleet' = c('Polyvalent Fleet - West Coast - Weeks',
                                 # 'Bottom Trawl Fleet - West Coast - Weeks',
                                 'Polyvalent Fleet - South Coast - Weeks',
                                 # 'Bottom Trawl Fleet - South Coast - Weeks',
                                 'Polyvalent Fleet - West Coast - Years',
                                 # 'Bottom Trawl Fleet - West Coast - Years',
                                 'Polyvalent Fleet - South Coast - Years'),
                                 # 'Bottom Trawl Fleet - South Coast - Years'),
                       'p-value' = estacionaridade,
                       'Estationary?' = ifelse(estacionaridade < 0.05, 'Yes', 'No'),
                       'Differentiation' = diferenca_ns,
                       'S. Differentiation' = diferenca_s)

# BoxCox.lambda(ts_w_MIS_S)
# tseries::kpss.test(ts_w_MIS_S)

xtable(tab_estac) %>% 
  print(.,
        type = "latex",
        file = "tables/res_estac.tex", 
        include.rownames = F,
        only.contents = T)



######## WEEKLY
dts_mis_w_w.train = window(ts_w_MIS_W, end=c(2020,52))
dts_mis_w_w.test=window(ts_w_MIS_W, start=c(2021,1), end=c(2022,52))

auto.arima(dts_mis_w_w.train) 
# (0,1,2)x(0,0,1)_52
sarima_mis_w_w.train = Arima(dts_mis_w_w.train,
                             order = c(0,1,2),
                             seasonal=list(order=c(0,0,1), period=52))
sarima_mis_w_w_forecast = forecast(sarima_mis_w_w.train,h=104)

###
dts_mis_s_w.train = window(ts_w_MIS_S, end=c(2020,52))
dts_mis_s_w.test=window(ts_w_MIS_S, start=c(2021,1), end=c(2022,52))

auto.arima(dts_mis_s_w.train) 
# (2,0,3)x(0,0,2)_52
sarima_mis_s_w.train = Arima(dts_mis_s_w.train,
                             order = c(2,0,3),
                             seasonal=list(order=c(0,0,2), period=52))
sarima_mis_s_w_forecast = forecast(sarima_mis_s_w.train,h=104)

######## YEARLY
dts_mis_w_y.train = window(ts_y_MIS_W, end=c(2020))
dts_mis_w_y.test=window(ts_y_MIS_W, start=c(2021), end=c(2022))

auto.arima(dts_mis_w_y.train) 
# (0,0,0)x(0,0,0)_1
sarima_mis_w_y.train = Arima(dts_mis_w_y.train,
                             order = c(0,0,0),
                             seasonal=list(order=c(0,0,0), period=1))
sarima_mis_w_y_forecast = forecast(sarima_mis_w_y.train,h=2)

###
dts_mis_s_y.train = window(ts_y_MIS_S, end=c(2020))
dts_mis_s_y.test=window(ts_y_MIS_S, start=c(2021), end=c(2022))

auto.arima(dts_mis_s_y.train) 
# (0,0,0)x(0,0,0)_1
sarima_mis_s_y.train = Arima(dts_mis_s_y.train,
                             order = c(0,0,0),
                             seasonal=list(order=c(0,0,0), period=1))
sarima_mis_s_y_forecast = forecast(sarima_mis_s_y.train,h=2)

b = Sys.time()
perf_boxjenkins_fit = b-a
```

# Output rendering

```{r}
a = Sys.time()

fig = 
grid.arrange(
  
autoplot(ts_w_MIS_W, col = col_mis_w) + theme_classic() + 
  labs(title = 'Weekly Series - Polyvalent fleet - West Coast',
       x = 'Year',
       y = 'landings (kg)'),   

autoplot(ts_w_MIS_S, col = col_mis_s) + theme_classic() + 
  labs(title = 'Weekly Series - Polyvalent fleet - South Coast',
       x = 'Year',
       y = 'landings (kg)'),

ncol = 1)

ggsave(fig, dpi = 300, width = 20, height = 20, units = 'cm', filename = 'plots/res_boxjenkins_weekly_series.png')

fig = 
grid.arrange(
  
autoplot(ts_y_MIS_W, col = col_mis_w) + theme_classic() + 
  labs(title = 'Yearly Series - Polyvalent fleet - West Coast',
       x = 'Year',
       y = 'landings (kg)'),
  
autoplot(ts_y_MIS_S, col = col_mis_s) + theme_classic() + 
  labs(title = 'Yearly Series - Polyvalent fleet - South Coast',
       x = 'Year',
       y = 'landings (kg)'),
	   
ncol = 1)

ggsave(fig, dpi = 300, width = 20, height = 20, units = 'cm', filename = 'plots/res_boxjenkins_yearly_series.png')

## ACF - Weekly

dev.new()
par(mfrow = c(2,2), cex.main = 3)
acf(ts_w_MIS_W, col = col_mis_w, main = 'West MIS - Weekly - ACF', lwd = 5);
pacf(ts_w_MIS_W, col = col_mis_w, main = 'West MIS - Weekly - pACF', lwd = 5)
acf(ts_w_MIS_S, col = col_mis_s, main = 'South MIS - Weekly - ACF', lwd = 5);
pacf(ts_w_MIS_S, col = col_mis_s, main = 'South MIS - Weekly - pACF', lwd = 5)
# acf(ts_w_OTB_W, col = col_otb_w, main = 'West OTB - Weekly - ACF', lwd = 5);
# pacf(ts_w_OTB_W, col = col_otb_w, main = 'West OTB - Weekly - pACF', lwd = 5)

grid.echo()
fig = grid.grab()
ggsave(fig, dpi = 300, units = 'cm', width = 20, height = 20,
       filename = 'plots/res_boxjenkins_week_W_acf.png')


dev.new()
par(mfrow = c(2,2), cex.main = 3)
acf(ts_y_MIS_W, col = col_mis_w, main = 'West MIS - Yearly - ACF', lwd = 5);
pacf(ts_y_MIS_W, col = col_mis_w, main = 'West MIS - Yearly - pACF', lwd = 5)
acf(ts_y_MIS_S, col = col_mis_s, main = 'South MIS - Yearly - ACF', lwd = 5);
pacf(ts_y_MIS_S, col = col_mis_s, main = 'South MIS - Yearly - pACF', lwd = 5)

grid.echo()
fig = grid.grab()

ggsave(fig, dpi = 300, width = 20, height = 20, units = 'cm', filename = 'plots/res_boxjenkins_year_W_acf.png')

# Forecasts

fig = 
gridExtra::grid.arrange(
  autoplot(sarima_mis_w_w_forecast,
         alpha = 1,
         size = 0.5,
         col = col_mis_w,
         fcol = col_otb_w) +
    labs(title = expression('SARIMA(0,1,2)*(0,0,1)'[52])) +
    theme_light(),
  autoplot(dts_mis_w_w.train, col = col_mis_w) +
  autolayer(dts_mis_w_w.test, color = col_otb_w,
          linetype = 'dashed') +
  labs(title = 'Real Data', y = 'catch (kg)') +
  theme_light(),
ncol=1)

ggsave(fig, dpi = 300, width = 20, height = 20, units = 'cm', filename = 'plots/res_boxjenkins_forecast_mis_w_w.png')

fig = 
gridExtra::grid.arrange(
  autoplot(sarima_mis_s_w_forecast,
         alpha = 1,
         size = 0.5,
         col = col_mis_s,
         fcol = col_otb_s) +
    labs(title = expression('SARIMA(2,0,3)*(0,0,2)'[52]), y = 'catch (kg)') +
    theme_light(),
  autoplot(dts_mis_s_w.train, col = col_mis_s) +
  autolayer(dts_mis_s_w.test, color = col_otb_s,
          linetype = 'dashed') +
  labs(title = 'Real Data', y = 'catch (kg)') +
  theme_light(),
ncol=1)

ggsave(fig, dpi = 300, width = 20, height = 20, units = 'cm', filename = 'plots/res_boxjenkins_forecast_mis_s_w.png')

fig = 
gridExtra::grid.arrange(
  autoplot(sarima_mis_w_y_forecast,
         alpha = 1,
         size = 0.5,
         col = col_mis_w,
         fcol = col_otb_w) +
    labs(title = expression('SARIMA(0,0,0)*(0,0,0)'[1]), y = 'catch (kg)') +
    theme_light(),
  autoplot(dts_mis_w_y.train, col = col_mis_w) +
  autolayer(dts_mis_w_y.test, color = col_otb_w,
          linetype = 'dashed') +
  labs(title = 'Real Data', y = 'catch (kg)') +
  theme_light(),
ncol=1)

ggsave(fig, dpi = 300, width = 20, height = 20, units = 'cm', filename = 'plots/res_boxjenkins_forecast_mis_w_y.png')

fig = 
gridExtra::grid.arrange(
  autoplot(sarima_mis_s_y_forecast,
         alpha = 1,
         size = 0.5,
         col = col_mis_s,
         fcol = col_otb_s) +
    labs(title = expression('SARIMA(0,0,0)*(0,0,0)'[1]), y = 'catch (kg)') +
    theme_light(),
  autoplot(dts_mis_s_y.train, col = col_mis_s) +
  autolayer(dts_mis_s_y.test, color = col_otb_s,
          linetype = 'dashed') +
  labs(title = 'Real Data', y = 'catch (kg)') +
  theme_light(),
ncol=1)

ggsave(fig, dpi = 300, width = 20, height = 20, units = 'cm', filename = 'plots/res_boxjenkins_forecast_mis_s_y.png')

b = Sys.time()
perf_boxjenkins_render = b-a
```

# Performance assessment

```{r}
perf_box_jenkins = data.frame('Framework' = 'Box Jenkins - Polivalent,  West + South, Yearly + Weekly data',
                              'Pre-process' = perf_boxjenkins_preproc,
                              'Model fit' = perf_boxjenkins_fit,
                              'Output Render' = perf_boxjenkins_render)
save(perf_box_jenkins, file = 'benchmarks/boxjenkins.Rdata')
```

