---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(ggplot2)
library(tidyr)
library(imputeTS)
library(CatDyn)
library(xtable)
```

```{r}
source('scripts/0010_importa_biologicas_sic.R')
source('scripts/0020_importa_biologicas_naut.R')
source('scripts/0030_junta_biologicas_sic_e_naut_calculca_regressoes.R')
source('scripts/0040_importa_dados_concurrent_sampling_sic.R')
source('scripts/0050_importa_dados_concurrent_sampling_naut.R')
source('scripts/0060_combina_dados_concurrent_sic_naut_converte_pesos_comp.R')
# save(bio_tmp, naut_peso, file = 'data/catdyn/bio_catdyn.Rdata')
```

```{r}
load('data/catdyn/bio_catdyn.Rdata')
load('data/initial_data_occ_df_final.Rdata')
```


# Preprocessment


```{r}

# arranjador_bio = function(df){
#   temp = df %>%
#     mutate(regiao = case_when(as.character(REGIAO) %in% 
#                               c('27.9.a.c.s', '27.9.a.c.n') ~ 'Western Coast',
#                             as.character(REGIAO) == '27.9.a.s.a' ~ 'Southern Coast',
#                             T ~ as.character(REGIAO)))
#   return(temp)
# }

naut_peso2 =
naut_peso %>%
    mutate(regiao = case_when(as.character(REGIAO) %in% 
                              c('27.9.a.c.s', '27.9.a.c.n') ~ 'Western Coast',
                            as.character(REGIAO) == '27.9.a.s.a' ~ 'Southern Coast',
                            T ~ as.character(REGIAO)),
  # mutate(id_caixa = case_when(is.na(id_caixa) ~ paste0(id_viagem, cat_com),
  #                             T ~ as.character(id_caixa)),
         semana = lubridate::isoweek(DATA))




contabilidade_w =
naut_peso2 %>%
  filter(regiao == 'Western Coast') %>% 
  group_by(id_caixa,semana, ANO) %>% 
  summarise(peso_am = unique(peso_am_caixa),
            n_am = sum(n_nao_observados)) %>% 
  group_by(semana,ANO) %>% 
  summarise(peso = sum(peso_am),
            n = sum(n_am),
            mean_weight = peso/n)
contabilidade_w$ANO = factor(contabilidade_w$ANO)
contabilidade_w$ANO = droplevels(contabilidade_w$ANO) 
contabilidade_w = complete(contabilidade_w, ANO)
contabilidade_w = contabilidade_w %>%
  arrange(ANO, semana) %>%
  mutate(time =as.numeric(as.character(ANO))+as.numeric(semana)/52)
contabilidade_w$mean_weight_estim = na_interpolation(contabilidade_w$mean_weight)

contabilidade_s =
naut_peso2 %>%
  filter(regiao == 'Southern Coast') %>% 
  group_by(id_caixa,semana, ANO) %>% 
  summarise(peso_am = unique(peso_am_caixa),
            n_am = sum(n_nao_observados)) %>% 
  group_by(semana,ANO) %>% 
  summarise(peso = sum(peso_am),
            n = sum(n_am),
            mean_weight = peso/n)
contabilidade_s$ANO = factor(contabilidade_s$ANO)
contabilidade_s$ANO = droplevels(contabilidade_s$ANO) 
contabilidade_s = complete(contabilidade_s, ANO)
contabilidade_s = contabilidade_s %>%
  arrange(ANO, semana) %>%
  mutate(time =as.numeric(as.character(ANO))+as.numeric(semana)/52)
contabilidade_s$mean_weight_estim = na_interpolation(contabilidade_s$mean_weight)


# df_w_12 =
# df_effort_w %>% 
#   filter(fill == '1-Western Coast 1-Polyvalent') %>% 
#   filter(year_sale == 2012) %>% 
#   left_join(.,
#             contabilidade_w %>% 
#               filter(ANO == 2012),
#             by = 'semana')
# 
# df_w_13 =
# df_effort_w %>% 
#   filter(fill == '1-Western Coast 1-Polyvalent') %>% 
#   filter(year_sale == 2013) %>% 
#   left_join(.,
#             contabilidade_w %>% 
#               filter(ANO == 2013),
#             by = 'semana')
# 
# df_w_14 =
# df_effort_w %>% 
#   filter(fill == '1-Western Coast 1-Polyvalent') %>% 
#   filter(year_sale == 2014) %>% 
#   left_join(.,
#             contabilidade_w %>% 
#               filter(ANO == 2014),
#             by = 'semana')
# 
# df_w_15 =
# df_effort_w %>% 
#   filter(fill == '1-Western Coast 1-Polyvalent') %>% 
#   filter(year_sale == 2015) %>% 
#   left_join(.,
#             contabilidade_w %>% 
#               filter(ANO == 2015),
#             by = 'semana')
# 
# df_w_16 =
# df_effort_w %>% 
#   filter(fill == '1-Western Coast 1-Polyvalent') %>% 
#   filter(year_sale == 2016) %>% 
#   left_join(.,
#             contabilidade_w %>% 
#               filter(ANO == 2016),
#             by = 'semana')
# 
# df_w_17 =
# df_effort_w %>% 
#   filter(fill == '1-Western Coast 1-Polyvalent') %>% 
#   filter(year_sale == 2017) %>% 
#   left_join(.,
#             contabilidade_w %>% 
#               filter(ANO == 2017),
#             by = 'semana')
# 
# df_w_18 =
# df_effort_w %>% 
#   filter(fill == '1-Western Coast 1-Polyvalent') %>% 
#   filter(year_sale == 2018) %>% 
#   left_join(.,
#             contabilidade_w %>% 
#               filter(ANO == 2018),
#             by = 'semana')
# 
# df_w_19 =
# df_effort_w %>% 
#   filter(fill == '1-Western Coast 1-Polyvalent') %>% 
#   filter(year_sale == 2019) %>% 
#   left_join(.,
#             contabilidade_w %>% 
#               filter(ANO == 2019),
#             by = 'semana')
# df_w_20 =
# df_effort_w %>% 
#   filter(fill == '1-Western Coast 1-Polyvalent') %>% 
#   filter(year_sale == 2020) %>% 
#   left_join(.,
#             contabilidade_w %>% 
#               filter(ANO == 2020),
#             by = 'semana')
# 
# df_w_21 =
# df_effort_w %>% 
#   filter(fill == '1-Western Coast 1-Polyvalent') %>% 
#   filter(year_sale == 2021) %>% 
#   left_join(.,
#             contabilidade_w %>% 
#               filter(ANO == 2021),
#             by = 'semana')
# 
df_w_22 =
df_effort_w %>%
  filter(fill == '1-Western Coast 1-Polyvalent') %>%
  filter(year_sale == 2022) %>%
  left_join(.,
            contabilidade_w %>%
              filter(ANO == 2022),
            by = 'semana')
# 
# df_s_12 =
# df_effort_w %>% 
#   filter(fill == '2-Southern Coast 1-Polyvalent') %>% 
#   filter(year_sale == 2012) %>% 
#   left_join(.,
#             contabilidade_s %>% 
#               filter(ANO == 2012),
#             by = 'semana')
# 
# df_s_13 =
# df_effort_w %>% 
#   filter(fill == '2-Southern Coast 1-Polyvalent') %>% 
#   filter(year_sale == 2013) %>% 
#   left_join(.,
#             contabilidade_s %>% 
#               filter(ANO == 2013),
#             by = 'semana')
# 
# df_s_14 =
# df_effort_w %>% 
#   filter(fill == '2-Southern Coast 1-Polyvalent') %>% 
#   filter(year_sale == 2014) %>% 
#   left_join(.,
#             contabilidade_s %>% 
#               filter(ANO == 2014),
#             by = 'semana')
# 
# df_s_15 =
# df_effort_w %>%
#   filter(semana != 53) %>% 
#   filter(fill == '2-Southern Coast 1-Polyvalent') %>% 
#   filter(year_sale == 2015) %>% 
#   left_join(.,
#             contabilidade_s %>% 
#               filter(ANO == 2015),
#             by = 'semana')
# 
# df_s_16 =
# df_effort_w %>% 
#   filter(fill == '2-Southern Coast 1-Polyvalent') %>% 
#   filter(year_sale == 2016) %>% 
#   left_join(.,
#             contabilidade_s %>% 
#               filter(ANO == 2016),
#             by = 'semana')
# 
# df_s_17 =
# df_effort_w %>% 
#   filter(fill == '2-Southern Coast 1-Polyvalent') %>% 
#   filter(year_sale == 2017) %>% 
#   left_join(.,
#             contabilidade_s %>% 
#               filter(ANO == 2017),
#             by = 'semana')
# 
# df_s_18 =
# df_effort_w %>% 
#   filter(fill == '2-Southern Coast 1-Polyvalent') %>% 
#   filter(year_sale == 2018) %>% 
#   left_join(.,
#             contabilidade_s %>% 
#               filter(ANO == 2018),
#             by = 'semana')
# 
# df_s_19 =
# df_effort_w %>% 
#   filter(fill == '2-Southern Coast 1-Polyvalent') %>% 
#   filter(year_sale == 2019) %>% 
#   left_join(.,
#             contabilidade_s %>% 
#               filter(ANO == 2019),
#             by = 'semana')
# df_s_20 =
# df_effort_w %>% 
#   filter(fill == '2-Southern Coast 1-Polyvalent') %>% 
#   filter(year_sale == 2020) %>% 
#   left_join(.,
#             contabilidade_s %>% 
#               filter(ANO == 2020),
#             by = 'semana')
# 
# df_s_21 =
# df_effort_w %>% 
#   filter(fill == '2-Southern Coast 1-Polyvalent') %>% 
#   filter(year_sale == 2021) %>% 
#   left_join(.,
#             contabilidade_s %>% 
#               filter(ANO == 2021),
#             by = 'semana')

df_s_22 =
df_effort_w %>% 
  filter(fill == '2-Southern Coast 1-Polyvalent') %>% 
  filter(year_sale == 2022) %>% 
  left_join(.,
            contabilidade_s %>% 
              filter(ANO == 2022),
            by = 'semana')

# cat_w_12 = as.CatDynData(x=df_w_12,
#                            step="week",
#                            fleet.name="Polyvalent-W",
#                            coleff=7,
#                            colcat=5,
#                            colmbw=15,
#                            unitseff="trips",
#                            unitscat="kg",
#                            unitsmbw="kg",
#                            nmult="thou",
#                            season.dates=c(as.Date("2012-01-01"),
#                                           as.Date("2012-12-23")))
# 
# cat_w_13 = as.CatDynData(x=df_w_13,
#                            step="week",
#                            fleet.name="Polyvalent-W-2013",
#                            coleff=7,
#                            colcat=5,
#                            colmbw=15,
#                            unitseff="trips",
#                            unitscat="kg",
#                            unitsmbw="kg",
#                            nmult="thou",
#                            season.dates=c(as.Date("2013-01-01"),
#                                           as.Date("2013-12-25")))
# 
# cat_w_14 = as.CatDynData(x=df_w_14,
#                            step="week",
#                            fleet.name="Polyvalent-W-2014",
#                            coleff=7,
#                            colcat=5,
#                            colmbw=15,
#                            unitseff="trips",
#                            unitscat="kg",
#                            unitsmbw="kg",
#                            nmult="thou",
#                            season.dates=c(as.Date("2014-01-01"),
#                                           as.Date("2014-12-25")))
# 
# cat_w_15 = as.CatDynData(x=df_w_15,
#                            step="week",
#                            fleet.name="Polyvalent-W-2015",
#                            coleff=7,
#                            colcat=5,
#                            colmbw=15,
#                            unitseff="trips",
#                            unitscat="kg",
#                            unitsmbw="kg",
#                            nmult="thou",
#                            season.dates=c(as.Date("2015-01-01"),
#                                           as.Date("2015-12-28")))
# 
# cat_w_16 = as.CatDynData(x=df_w_16,
#                            step="week",
#                            fleet.name="Polyvalent-W-2016",
#                            coleff=7,
#                            colcat=5,
#                            colmbw=15,
#                            unitseff="trips",
#                            unitscat="kg",
#                            unitsmbw="kg",
#                            nmult="thou",
#                            season.dates=c(as.Date("2016-01-01"),
#                                           as.Date("2016-12-28")))
# 
# cat_w_17 = as.CatDynData(x=df_w_17,
#                            step="week",
#                            fleet.name="Polyvalent-W-2017",
#                            coleff=7,
#                            colcat=5,
#                            colmbw=15,
#                            unitseff="trips",
#                            unitscat="kg",
#                            unitsmbw="kg",
#                            nmult="thou",
#                            season.dates=c(as.Date("2017-01-01"),
#                                           as.Date("2017-12-24")))
# 
# cat_w_18 = as.CatDynData(x=df_w_18,
#                            step="week",
#                            fleet.name="Polyvalent-W-2018",
#                            coleff=7,
#                            colcat=5,
#                            colmbw=15,
#                            unitseff="trips",
#                            unitscat="kg",
#                            unitsmbw="kg",
#                            nmult="thou",
#                            season.dates=c(as.Date("2018-01-01"),
#                                           as.Date("2018-12-28")))
# 
# cat_w_19 = as.CatDynData(x=df_w_19,
#                            step="week",
#                            fleet.name="Polyvalent-W-2019",
#                            coleff=7,
#                            colcat=5,
#                            colmbw=15,
#                            unitseff="trips",
#                            unitscat="kg",
#                            unitsmbw="kg",
#                            nmult="thou",
#                            season.dates=c(as.Date("2019-01-01"),
#                                           as.Date("2019-12-28")))
# 
# cat_w_20 = as.CatDynData(x=df_w_20,
#                            step="week",
#                            fleet.name="Polyvalent-W-2020",
#                            coleff=7,
#                            colcat=5,
#                            colmbw=15,
#                            unitseff="trips",
#                            unitscat="kg",
#                            unitsmbw="kg",
#                            nmult="thou",
#                            season.dates=c(as.Date("2020-01-01"),
#                                           as.Date("2020-12-28")))
# 
# cat_w_21 = as.CatDynData(x=df_w_21,
#                            step="week",
#                            fleet.name="Polyvalent-W-2021",
#                            coleff=7,
#                            colcat=5,
#                            colmbw=15,
#                            unitseff="trips",
#                            unitscat="kg",
#                            unitsmbw="kg",
#                            nmult="thou",
#                            season.dates=c(as.Date("2021-01-01"),
#                                           as.Date("2021-12-28")))
cat_w_22 = as.CatDynData(x=df_w_22,
                           step="week",
                           fleet.name="Polyvalent-W-2022",
                           coleff=7,
                           colcat=5,
                           colmbw=15,
                           unitseff="trips",
                           unitscat="kg",
                           unitsmbw="kg",
                           nmult="thou",
                           season.dates=c(as.Date("2022-01-01"),
                                          as.Date("2022-12-25")))


###############

# cat_s_12 = as.CatDynData(x=df_s_12,
#                            step="week",
#                            fleet.name="Polyvalent-S-2012",
#                            coleff=7,
#                            colcat=5,
#                            colmbw=15,
#                            unitseff="trips",
#                            unitscat="kg",
#                            unitsmbw="kg",
#                            nmult="thou",
#                            season.dates=c(as.Date("2012-01-01"),
#                                           as.Date("2012-12-23")))
# 
# cat_s_13 = as.CatDynData(x=df_s_13,
#                            step="week",
#                            fleet.name="Polyvalent-S-2013",
#                            coleff=7,
#                            colcat=5,
#                            colmbw=15,
#                            unitseff="trips",
#                            unitscat="kg",
#                            unitsmbw="kg",
#                            nmult="thou",
#                            season.dates=c(as.Date("2013-01-01"),
#                                           as.Date("2013-12-25")))
# 
# cat_s_14 = as.CatDynData(x=df_s_14,
#                            step="week",
#                            fleet.name="Polyvalent-S-2014",
#                            coleff=7,
#                            colcat=5,
#                            colmbw=15,
#                            unitseff="trips",
#                            unitscat="kg",
#                            unitsmbw="kg",
#                            nmult="thou",
#                            season.dates=c(as.Date("2014-01-01"),
#                                           as.Date("2014-12-25")))
# 
# cat_s_15 = as.CatDynData(x=df_s_15,
#                            step="week",
#                            fleet.name="Polyvalent-S-2015",
#                            coleff=7,
#                            colcat=5,
#                            colmbw=15,
#                            unitseff="trips",
#                            unitscat="kg",
#                            unitsmbw="kg",
#                            nmult="thou",
#                            season.dates=c(as.Date("2015-01-01"),
#                                           as.Date("2015-12-27")))
# 
# cat_s_16 = as.CatDynData(x=df_s_16,
#                            step="week",
#                            fleet.name="Polyvalent-S-2016",
#                            coleff=7,
#                            colcat=5,
#                            colmbw=15,
#                            unitseff="trips",
#                            unitscat="kg",
#                            unitsmbw="kg",
#                            nmult="thou",
#                            season.dates=c(as.Date("2016-01-01"),
#                                           as.Date("2016-12-25")))
# 
# cat_s_17 = as.CatDynData(x=df_s_17,
#                            step="week",
#                            fleet.name="Polyvalent-S-2017",
#                            coleff=7,
#                            colcat=5,
#                            colmbw=15,
#                            unitseff="trips",
#                            unitscat="kg",
#                            unitsmbw="kg",
#                            nmult="thou",
#                            season.dates=c(as.Date("2017-01-01"),
#                                           as.Date("2017-12-24")))
# 
# cat_s_18 = as.CatDynData(x=df_s_18,
#                            step="week",
#                            fleet.name="Polyvalent-S-2018",
#                            coleff=7,
#                            colcat=5,
#                            colmbw=15,
#                            unitseff="trips",
#                            unitscat="kg",
#                            unitsmbw="kg",
#                            nmult="thou",
#                            season.dates=c(as.Date("2018-01-01"),
#                                           as.Date("2018-12-28")))
# 
# cat_s_19 = as.CatDynData(x=df_s_19,
#                            step="week",
#                            fleet.name="Polyvalent-S-2019",
#                            coleff=7,
#                            colcat=5,
#                            colmbw=15,
#                            unitseff="trips",
#                            unitscat="kg",
#                            unitsmbw="kg",
#                            nmult="thou",
#                            season.dates=c(as.Date("2019-01-01"),
#                                           as.Date("2019-12-28")))
# 
# cat_s_20 = as.CatDynData(x=df_s_20 %>% filter(semana != 53),
#                            step="week",
#                            fleet.name="Polyvalent-S-2020",
#                            coleff=7,
#                            colcat=5,
#                            colmbw=15,
#                            unitseff="trips",
#                            unitscat="kg",
#                            unitsmbw="kg",
#                            nmult="thou",
#                            season.dates=c(as.Date("2020-01-01"),
#                                           as.Date("2020-12-27")))
# 
# cat_s_21 = as.CatDynData(x=df_s_21,
#                            step="week",
#                            fleet.name="Polyvalent-S-2021",
#                            coleff=7,
#                            colcat=5,
#                            colmbw=15,
#                            unitseff="trips",
#                            unitscat="kg",
#                            unitsmbw="kg",
#                            nmult="thou",
#                            season.dates=c(as.Date("2021-01-01"),
#                                           as.Date("2021-12-26")))
cat_s_22 = as.CatDynData(x=df_s_22,
                           step="week",
                           fleet.name="Polyvalent-S-2022",
                           coleff=7,
                           colcat=5,
                           colmbw=15,
                           unitseff="trips",
                           unitscat="kg",
                           unitsmbw="kg",
                           nmult="thou",
                           season.dates=c(as.Date("2022-01-01"),
                                          as.Date("2022-12-25")))

```

# teste dos mean weights

```{r}
contabilidade_s %>%
  # filter(ANO == 2017) %>% View()
  ggplot +
  geom_line(aes(x = semana,
                y = mean_weight_estim,
                group = ANO,
                color = ANO)) +
  # geom_smooth(aes(x = semana,
  #                 y =  mean_weight)) +
  facet_wrap(ANO~.) +
  labs(title = 'Costa SUL') +
  theme_bw()
```

# funcoes para fittar catdyn

```{r}
trialer = function(data, p,M, N0.ini, P.ini, k.ini,
                   alpha.ini, beta.ini, P,
                   distr, method, itnmax, disp = list()){
 
  pars.ini = log(c(M,
                   N0.ini,
                   unlist(P.ini),
                   k.ini,
                   alpha.ini,
                   beta.ini,
                   unlist(disp)))
  
  dates = c(head(data$Data[[1]]$time.step,1),
           unlist(P),
           tail(data$Data[[1]]$time.step,1))
  
  res = list()
  
  res$pre_fit = catdynexp(x=data,
                          p=p,
                          par=pars.ini,
                          dates=dates,
                          distr=distr)
  
  res$fit = CatDynFit(x = data,
                  p = p,
                  par = pars.ini,
                  dates = dates,
                  distr = distr,
                  method = method,
                  itnmax = itnmax)
  
  res$pred = CatDynPred(res$fit,method)
  
  return(res)
}

plotador = function(data, model){
  plot.CatDynData(data,
                mark = T,
                offset = c(0,1,10),
                hem = 'N')
  
  plot(x=model$pre_fit,
     leg.pos="topright",
     Biom.tstep=7,
     Cat.tstep=120,
     Biom.xpos=0.4,
     Biom.ypos=0,
     Cat.xpos=0.4,
     Cat.ypos=0.1)

  plot(x=model$pred,
       leg.pos="topright",
       Biom.tstep=7,
       Cat.tstep=10,
       Biom.xpos=0.18,
       Biom.ypos=0.1,
       Cat.xpos=0.18,
       Cat.ypos=0.2)
    
}
```


## Fit - 2022 W

```{r}
plot.CatDynData(cat_w_22,
                mark = T,
                offset = c(0,1,10),
                hem = 'N')
```
despiste several catch maxima,at week 2, 17 26 or 43, catch spike maxima is 43. 

```{r}

# poisson", "negbin", "normal", "apnormal", "lognormal", "aplnormal", "gamma", "roblognormal", "gumbel"

# Nelder-Mead', 'BFGS', 'CG', 'L-BFGS-B', 'nlm', 'nlminb', 'spg', 'ucminf', 'newuoa', 'bobyqa', 'nmkb', 'hjkb', 'Rcgmin', or 'Rvmmin'



# negbin, normal, lognormal, gamma

# CG - spg - BFGS - Nelder-Mead



fit_w_22_1 = 
  trialer(cat_w_22,
        p = 1,
        M = 1/52,
        N0.ini = 15000,
        P.ini = list(1000),
        k.ini = 0.01,
        alpha.ini = 0.5,
        beta.ini  = 0.5,
        P = list(43),
        distr = 'negbin',
        method = 'CG',
        itnmax = 100000,
        disp = 50)

fit_w_22_2 = 
  trialer(cat_w_22,
        p = 1,
        M = 1/52,
        N0.ini = 15000,
        P.ini = list(1000),
        k.ini = 0.01,
        alpha.ini = 0.5,
        beta.ini  = 0.5,
        P = list(43),
        distr = 'negbin',
        method = 'spg',
        itnmax = 100000,
        disp = 50)

fit_w_22_3 = 
  trialer(cat_w_22,
        p = 1,
        M = 1/52,
        N0.ini = 15000,
        P.ini = list(1000),
        k.ini = 0.01,
        alpha.ini = 0.5,
        beta.ini  = 0.5,
        P = list(43),
        distr = 'negbin',
        method = 'BFGS',
        itnmax = 100000,
        disp = 50)

fit_w_22_4 = 
  trialer(cat_w_22,
        p = 1,
        M = 1/52,
        N0.ini = 15000,
        P.ini = list(1000),
        k.ini = 0.01,
        alpha.ini = 0.5,
        beta.ini  = 0.5,
        P = list(43),
        distr = 'negbin',
        method = 'Nelder-Mead',
        itnmax = 100000,
        disp = 50)

fit_w_22_5 = 
  trialer(cat_w_22,
        p = 1,
        M = 1/52,
        N0.ini = 15000,
        P.ini = list(1000),
        k.ini = 0.01,
        alpha.ini = 0.5,
        beta.ini  = 0.5,
        P = list(43),
        distr = 'normal',
        method = 'CG',
        itnmax = 100000,
        disp = 50)

fit_w_22_6 = 
  trialer(cat_w_22,
        p = 1,
        M = 1/52,
        N0.ini = 15000,
        P.ini = list(1000),
        k.ini = 0.01,
        alpha.ini = 0.5,
        beta.ini  = 0.5,
        P = list(43),
        distr = 'normal',
        method = 'spg',
        itnmax = 100000,
        disp = 50)

fit_w_22_7 = 
  trialer(cat_w_22,
        p = 1,
        M = 1/52,
        N0.ini = 15000,
        P.ini = list(1000),
        k.ini = 0.01,
        alpha.ini = 0.5,
        beta.ini  = 0.5,
        P = list(43),
        distr = 'normal',
        method = 'BFGS',
        itnmax = 100000,
        disp = 50)

fit_w_22_8 = 
  trialer(cat_w_22,
        p = 1,
        M = 1/52,
        N0.ini = 15000,
        P.ini = list(1000),
        k.ini = 0.01,
        alpha.ini = 0.5,
        beta.ini  = 0.5,
        P = list(43),
        distr = 'normal',
        method = 'Nelder-Mead',
        itnmax = 100000,
        disp = 50)

fit_w_22_9 = 
  trialer(cat_w_22,
        p = 1,
        M = 1/52,
        N0.ini = 15000,
        P.ini = list(1000),
        k.ini = 0.01,
        alpha.ini = 0.5,
        beta.ini  = 0.5,
        P = list(43),
        distr = 'lognormal',
        method = 'CG',
        itnmax = 100000,
        disp = 50)

fit_w_22_10 = 
  trialer(cat_w_22,
        p = 1,
        M = 1/52,
        N0.ini = 15000,
        P.ini = list(1000),
        k.ini = 0.01,
        alpha.ini = 0.5,
        beta.ini  = 0.5,
        P = list(43),
        distr = 'lognormal',
        method = 'spg',
        itnmax = 100000,
        disp = 50)

fit_w_22_11 = 
  trialer(cat_w_22,
        p = 1,
        M = 1/52,
        N0.ini = 15000,
        P.ini = list(1000),
        k.ini = 0.01,
        alpha.ini = 0.5,
        beta.ini  = 0.5,
        P = list(43),
        distr = 'lognormal',
        method = 'BFGS',
        itnmax = 100000,
        disp = 50)

fit_w_22_12 = 
  trialer(cat_w_22,
        p = 1,
        M = 1/52,
        N0.ini = 15000,
        P.ini = list(1000),
        k.ini = 0.01,
        alpha.ini = 0.5,
        beta.ini  = 0.5,
        P = list(43),
        distr = 'lognormal',
        method = 'Nelder-Mead',
        itnmax = 100000,
        disp = 50)

fit_w_22_13 = 
  trialer(cat_w_22,
        p = 1,
        M = 1/52,
        N0.ini = 15000,
        P.ini = list(1000),
        k.ini = 0.01,
        alpha.ini = 0.5,
        beta.ini  = 0.5,
        P = list(43),
        distr = 'gamma',
        method = 'CG',
        itnmax = 100000,
        disp = 50)

fit_w_22_14 = 
  trialer(cat_w_22,
        p = 1,
        M = 1/52,
        N0.ini = 15000,
        P.ini = list(1000),
        k.ini = 0.01,
        alpha.ini = 0.5,
        beta.ini  = 0.5,
        P = list(43),
        distr = 'gamma',
        method = 'spg',
        itnmax = 100000,
        disp = 50)

fit_w_22_15 = 
  trialer(cat_w_22,
        p = 1,
        M = 1/52,
        N0.ini = 15000,
        P.ini = list(1000),
        k.ini = 0.01,
        alpha.ini = 0.5,
        beta.ini  = 0.5,
        P = list(43),
        distr = 'gamma',
        method = 'BFGS',
        itnmax = 100000,
        disp = 50)

fit_w_22_16 = 
  trialer(cat_w_22,
        p = 1,
        M = 1/52,
        N0.ini = 15000,
        P.ini = list(1000),
        k.ini = 0.01,
        alpha.ini = 0.5,
        beta.ini  = 0.5,
        P = list(43),
        distr = 'gamma',
        method = 'Nelder-Mead',
        itnmax = 100000,
        disp = 50)


CatDynSum(x = list(fit_w_22_1$fit,
                   fit_w_22_2$fit,
                   fit_w_22_3$fit,
                   fit_w_22_4$fit,
                   fit_w_22_5$fit,
                   fit_w_22_6$fit,
                   fit_w_22_7$fit,
                   # fit_w_22_8$fit,
                   fit_w_22_9$fit,
                   fit_w_22_10$fit,
                   # fit_w_22_11$fit,
                   fit_w_22_12$fit,
                   fit_w_22_13$fit,
                   fit_w_22_14$fit,
                   fit_w_22_15$fit,
                   fit_w_22_16$fit),
          season = '2022',
          method = c('CG','spg','BFGS','Nelder-Mead',
                     'CG','spg','BFGS',#'Nelder-Mead',
                     'CG','spg',#'BFGS',
                     'Nelder-Mead',
                     'CG','spg','BFGS','Nelder-Mead')) %>% View


#fit_w_22
plotador(cat_w_22, fit_w_22)


```




# Fit do sul

```{r}
plot.CatDynData(cat_s_22,
                mark = T,
                offset = c(0,1,10),
                hem = 'N')
```
Spike at week 2 in the series


```{r}
fit_s_22_1 = 
  trialer(cat_s_22,
        p = 1,
        M = 1/52,
        N0.ini = 15000,
        P.ini = list(1000),
        k.ini = 0.01,
        alpha.ini = 0.5,
        beta.ini  = 0.5,
        P = list(2),
        distr = 'negbin',
        method = 'CG',
        itnmax = 100000,
        disp = 50)

fit_s_22_2 = 
  trialer(cat_s_22,
        p = 1,
        M = 1/52,
        N0.ini = 15000,
        P.ini = list(1000),
        k.ini = 0.01,
        alpha.ini = 0.5,
        beta.ini  = 0.5,
        P = list(2),
        distr = 'negbin',
        method = 'spg',
        itnmax = 100000,
        disp = 50)

fit_s_22_3 = 
  trialer(cat_s_22,
        p = 1,
        M = 1/52,
        N0.ini = 15000,
        P.ini = list(1000),
        k.ini = 0.01,
        alpha.ini = 0.5,
        beta.ini  = 0.5,
        P = list(2),
        distr = 'negbin',
        method = 'BFGS',
        itnmax = 100000,
        disp = 50)

fit_s_22_4 = 
  trialer(cat_s_22,
        p = 1,
        M = 1/52,
        N0.ini = 15000,
        P.ini = list(1000),
        k.ini = 0.01,
        alpha.ini = 0.5,
        beta.ini  = 0.5,
        P = list(2),
        distr = 'negbin',
        method = 'Nelder-Mead',
        itnmax = 100000,
        disp = 50)

fit_s_22_5 = 
  trialer(cat_s_22,
        p = 1,
        M = 1/52,
        N0.ini = 15000,
        P.ini = list(1000),
        k.ini = 0.01,
        alpha.ini = 0.5,
        beta.ini  = 0.5,
        P = list(2),
        distr = 'normal',
        method = 'CG',
        itnmax = 100000,
        disp = 50)

fit_s_22_6 = 
  trialer(cat_s_22,
        p = 1,
        M = 1/52,
        N0.ini = 15000,
        P.ini = list(1000),
        k.ini = 0.01,
        alpha.ini = 0.5,
        beta.ini  = 0.5,
        P = list(2),
        distr = 'normal',
        method = 'spg',
        itnmax = 100000,
        disp = 50)

fit_s_22_7 = 
  trialer(cat_s_22,
        p = 1,
        M = 1/52,
        N0.ini = 15000,
        P.ini = list(1000),
        k.ini = 0.01,
        alpha.ini = 0.5,
        beta.ini  = 0.5,
        P = list(2),
        distr = 'normal',
        method = 'BFGS',
        itnmax = 100000,
        disp = 50)

fit_s_22_8 = 
  trialer(cat_s_22,
        p = 1,
        M = 1/52,
        N0.ini = 15000,
        P.ini = list(1000),
        k.ini = 0.01,
        alpha.ini = 0.5,
        beta.ini  = 0.5,
        P = list(2),
        distr = 'normal',
        method = 'Nelder-Mead',
        itnmax = 100000,
        disp = 50)

fit_s_22_9 = 
  trialer(cat_s_22,
        p = 1,
        M = 1/52,
        N0.ini = 15000,
        P.ini = list(1000),
        k.ini = 0.01,
        alpha.ini = 0.5,
        beta.ini  = 0.5,
        P = list(2),
        distr = 'lognormal',
        method = 'CG',
        itnmax = 100000,
        disp = 50)

fit_s_22_10 = 
  trialer(cat_s_22,
        p = 1,
        M = 1/52,
        N0.ini = 15000,
        P.ini = list(1000),
        k.ini = 0.01,
        alpha.ini = 0.5,
        beta.ini  = 0.5,
        P = list(2),
        distr = 'lognormal',
        method = 'spg',
        itnmax = 100000,
        disp = 50)

fit_s_22_11 = 
  trialer(cat_s_22,
        p = 1,
        M = 1/52,
        N0.ini = 15000,
        P.ini = list(1000),
        k.ini = 0.01,
        alpha.ini = 0.5,
        beta.ini  = 0.5,
        P = list(2),
        distr = 'lognormal',
        method = 'BFGS',
        itnmax = 100000,
        disp = 50)

fit_s_22_12 = 
  trialer(cat_s_22,
        p = 1,
        M = 1/52,
        N0.ini = 15000,
        P.ini = list(1000),
        k.ini = 0.01,
        alpha.ini = 0.5,
        beta.ini  = 0.5,
        P = list(2),
        distr = 'lognormal',
        method = 'Nelder-Mead',
        itnmax = 100000,
        disp = 50)

fit_s_22_13 = 
  trialer(cat_s_22,
        p = 1,
        M = 1/52,
        N0.ini = 15000,
        P.ini = list(1000),
        k.ini = 0.01,
        alpha.ini = 0.5,
        beta.ini  = 0.5,
        P = list(2),
        distr = 'gamma',
        method = 'CG',
        itnmax = 100000,
        disp = 50)

fit_s_22_14 = 
  trialer(cat_s_22,
        p = 1,
        M = 1/52,
        N0.ini = 15000,
        P.ini = list(1000),
        k.ini = 0.01,
        alpha.ini = 0.5,
        beta.ini  = 0.5,
        P = list(2),
        distr = 'gamma',
        method = 'spg',
        itnmax = 100000,
        disp = 50)

fit_s_22_15 = 
  trialer(cat_s_22,
        p = 1,
        M = 1/52,
        N0.ini = 15000,
        P.ini = list(1000),
        k.ini = 0.01,
        alpha.ini = 0.5,
        beta.ini  = 0.5,
        P = list(2),
        distr = 'gamma',
        method = 'BFGS',
        itnmax = 100000,
        disp = 50)

fit_s_22_16 = 
  trialer(cat_s_22,
        p = 1,
        M = 1/52,
        N0.ini = 15000,
        P.ini = list(1000),
        k.ini = 0.01,
        alpha.ini = 0.5,
        beta.ini  = 0.5,
        P = list(2),
        distr = 'gamma',
        method = 'Nelder-Mead',
        itnmax = 100000,
        disp = 50)


summary_catdyn_s =
CatDynSum(x = list(fit_s_22_1$fit,
                   fit_s_22_2$fit,
                   fit_s_22_3$fit,
                   fit_s_22_4$fit,
                   fit_s_22_5$fit,
                   fit_s_22_6$fit,
                   fit_s_22_7$fit,
                   fit_s_22_8$fit,
                   fit_s_22_9$fit,
                   fit_s_22_10$fit,
                   fit_s_22_11$fit,
                   fit_s_22_12$fit,
                   fit_s_22_13$fit,
                   fit_s_22_14$fit,
                   fit_s_22_15$fit,
                   fit_s_22_16$fit),
          season = '2022',
          method = c('CG','spg','BFGS','Nelder-Mead',
                     'CG','spg','BFGS','Nelder-Mead',
                     'CG','spg','BFGS',
                     'Nelder-Mead',
                     'CG','spg','BFGS','Nelder-Mead')) 

xtable(summary_catdyn_s) %>% 
  print(.,
        type = "latex",
        file = "tables/res_catdyn_s.tex", 
        include.rownames = F,
        only.contents = T)

```


```{r}
fit_w_22 = 
  trialer(cat_w_22,
        p = 2,
        M = 1/52,
        N0.ini = 10000,
        P.ini = list(100, 100),
        k.ini = 0.1,
        alpha.ini = 0.1,
        beta.ini  = 0.11,
        P = list(8,36),
        distr = 'lognormal',
        method = 'spg',
        itnmax = 10,
        disp = 50)

plotador(cat_w_22, fit_w_22)

```



# deprecated

```{r, eval = F}

bw_sum_w = 
contabilidade_w %>% group_by(ANO) %>% 
  summarise(mbw = mean(mean_weight_estim, na.rm =T),
            mbw_sd = sd(mean_weight_estim, na.rm = T))

temp = data.frame(
rbind(bw_sum_w[1:3,],
      bw_sum_w[1:3,],
      bw_sum_w[1:3,],
      bw_sum_w[1:3,],
      bw_sum_w[1:3,]))
temp$ANO = 2008:2022

inp_s = list(fit_w_12$fit, fit_w_13$fit, fit_w_14$fit,
          fit_w_12$fit, fit_w_13$fit, fit_w_14$fit,
          fit_w_12$fit, fit_w_13$fit, fit_w_14$fit,
          fit_w_12$fit, fit_w_13$fit, fit_w_14$fit,
          fit_w_12$fit, fit_w_13$fit, fit_w_14$fit)

CatDynBSD(inp_s,
          multi = F,
          mbw.sd = temp,
          method = rep('spg',15))

contabilidade_w_m =
naut_peso2 %>%
  filter(regiao == 'Western Coast') %>% 
  group_by(id_caixa, MES, ANO) %>% 
  summarise(peso_am = unique(peso_am_caixa),
            n_am = sum(n_nao_observados,na.rm=T)) %>% 
  group_by(MES, ANO) %>% 
  summarise(peso = sum(peso_am,na.rm=T),
            n = sum(n_am,na.rm=T),
            mean_weight = peso/n)
contabilidade_w_m$ANO = factor(contabilidade_w_m$ANO)
contabilidade_w_m$ANO = droplevels(contabilidade_w_m$ANO) 
contabilidade_w_m = complete(contabilidade_w_m, ANO)
contabilidade_w_m = contabilidade_w_m %>% 
  arrange(ANO,MES) %>% 
  mutate(time =as.numeric(as.character(ANO))+as.numeric(MES)/12)
contabilidade_w_m$mean_weight_estim = na_interpolation(contabilidade_w_m$mean_weight)

temp =
df_effort_m %>% 
  filter(fill == '1-Western Coast 1-Polyvalent') %>% 
  left_join(contabilidade_w_m,
            by = c('year_sale' = 'ANO',
                   'month_sale' = 'MES'))

cat_w_mis = as.CatDynData(x=temp %>% ,
                           step="month",
                           fleet.name="Polyvalent-W",
                           coleff=7,
                           colcat=5,
                           colmbw=14,
                           unitseff="trips",
                           unitscat="kg",
                           unitsmbw="kg",
                           nmult="thou")
```


